name = "I'm thauming so hard rn"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fcf8082907fa7fd809c131eade35b316cdb2782a0ae9fc1103cd8d0696d4da2"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1.2"
