name = "I'm thauming so hard rn"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e9654cacb65febfd16e303cbf9e05fcaafafc50b1d8b49938468b6c8672dcc"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1.2"
